source 'https://github.com/CocoaPods/Specs.git'

target 'Spark-SDK', :exclusive => true do
  pod "Spark-SDK", :path => "../"
  pod 'AFNetworking'
end

target 'Tests', :exclusive => true do
  pod "Spark-SDK", :path => "../"

  
end
